version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: borea
      POSTGRES_PASSWORD: borea
      POSTGRES_DB: pg_borea
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local