version: '3.8'

services:
  postgres:
    build:
      context: ../postgres
      dockerfile: Dockerfile
    container_name: postgres
    volumes:
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - borea-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "borea", "-d", "pg_borea"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ../.env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - borea-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    env_file:
      - ../.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - borea-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  borea-network:
    driver: bridge
