# Use the official PostgreSQL image from Docker Hub
FROM postgres:17

# Set environment variables for database creation
ENV POSTGRES_DB=borea
ENV POSTGRES_USER=borea
ENV POSTGRES_PASSWORD=borea

COPY pg_init.sql /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432
